# For production: replace this with an ExternalSecret pulling from the secrets manager.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{ .Values.teamName }}
type: Opaque
stringData:
  username: {{ .Values.database.credentials.username }}
  password: {{ .Values.database.credentials.password | required "database.credentials.password is required" }}
  root-password: {{ .Values.database.credentials.rootPassword | required "database.credentials.rootPassword is required" }}
  url: "postgresql+asyncpg://{{ .Values.database.credentials.username }}:{{ .Values.database.credentials.password }}@{{ .Release.Name }}-db:5432/webapp"
