{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.teamName }}
  labels:
    {{- toYaml .Values.monitoring.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
