apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/platform/backstage/values-poc.yaml
    - repoURL: https://github.com/danielweber90/idp-poc
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
