apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  type: git
  url: git@github.com:${{ values.remoteUrl | replace("https://github.com/", "") }}.git
  sshPrivateKey: |
    ${{ values.sshPrivateKey | indent(4) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:${{ values.remoteUrl | replace("https://github.com/", "") }}.git
    targetRevision: main
    path: helm
    helm:
      releaseName: ${{ values.name }}
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team-${{ values.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
