apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: "${{ values.name }} — managed by IDP PoC"
  annotations:
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
    grafana/dashboard-selector: "app=${{ values.name }}"
    github.com/project-slug: danielweber90/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    slo/target: "${{ values.sloTarget }}"
  tags:
    - ${{ values.runtime }}
spec:
  type: service
  owner: group:default/${{ values.owner }}
  lifecycle: experimental
  dependsOn:
    {%- if values.postgresql.enabled %}
    - resource:default/${{ values.name }}-db
    {%- endif %}
    {%- if values.redis.enabled %}
    - resource:default/${{ values.name }}-redis
    {%- endif %}
    {%- if values.objectStorage.enabled %}
    - resource:default/${{ values.name }}-storage
    {%- endif %}
{%- if values.postgresql.enabled %}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-db
  description: "PostgreSQL database for ${{ values.name }} — provisioned by Crossplane → AWS RDS"
spec:
  type: database
  owner: group:default/${{ values.owner }}
{%- endif %}
{%- if values.redis.enabled %}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-redis
  description: "Redis cache for ${{ values.name }} — provisioned by Crossplane → AWS ElastiCache"
spec:
  type: cache
  owner: group:default/${{ values.owner }}
{%- endif %}
{%- if values.objectStorage.enabled %}
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}-storage
  description: "Object storage for ${{ values.name }} — provisioned by Crossplane → AWS S3"
spec:
  type: storage
  owner: group:default/${{ values.owner }}
{%- endif %}
