apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresqlinstance-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.idp-poc.io/v1alpha1
    kind: PostgreSQLInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: rds-instance
            base:
              apiVersion: rds.aws.upbound.io/v1beta1
              kind: Instance
              spec:
                forProvider:
                  region: eu-central-1
                  engine: postgres
                  engineVersion: "15"
                  instanceClass: db.t3.micro
                  allocatedStorage: 20
                  skipFinalSnapshot: true
                  publiclyAccessible: false
                  dbName: appdb
                  username: appuser
                  dbSubnetGroupName: idp-poc-db
                  vpcSecurityGroupIds:
                    - sg-04d755b373f1254ab
                  passwordSecretRef:
                    namespace: crossplane-system
                    name: demo-db-password
                    key: password
                writeConnectionSecretToRef:
                  namespace: crossplane-system
                  name: ""
            patches:
              - fromFieldPath: spec.parameters.size
                toFieldPath: spec.forProvider.instanceClass
                transforms:
                  - type: map
                    map:
                      small:  db.t3.micro
                      medium: db.t3.small
                      large:  db.t3.medium
              - fromFieldPath: spec.parameters.database
                toFieldPath: spec.forProvider.dbName
              - fromFieldPath: spec.parameters.username
                toFieldPath: spec.forProvider.username
              - fromFieldPath: spec.parameters.version
                toFieldPath: spec.forProvider.engineVersion
              - fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-rds-connection"
            connectionDetails:
              - name: endpoint
                type: FromConnectionSecretKey
                fromConnectionSecretKey: endpoint
              - name: username
                type: FromConnectionSecretKey
                fromConnectionSecretKey: username
              - name: password
                type: FromConnectionSecretKey
                fromConnectionSecretKey: password
              - name: database
                type: FromFieldPath
                fromFieldPath: spec.parameters.database
