# Kong Ingress Controller values for IDP PoC
controller:
  ingressClass: kong
  installCRDs: false

proxy:
  type: LoadBalancer
  annotations:
    # Terminate TLS at the CLB; forward HTTP to Kong
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:084375542523:certificate/8bdce501-08ba-4b1b-926c-e2fd85a6db64"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
