apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: objectstorageinstances.platform.idp-poc.io
spec:
  group: platform.idp-poc.io
  names:
    kind: ObjectStorageInstance
    plural: objectstorageinstances
  claimNames:
    kind: ObjectStorageClaim
    plural: objectstorageclaims
  connectionSecretKeys:
    - endpoint
    - bucketName
    - accessKey
    - secretKey

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [parameters]
              properties:
                parameters:
                  type: object
                  properties:
                    publicRead:
                      type: boolean
                      default: false
                    versioning:
                      type: boolean
                      default: false
                writeConnectionSecretToRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
