apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: postgresqlinstances.platform.idp-poc.io
spec:
  group: platform.idp-poc.io
  names:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  claimNames:
    kind: PostgreSQLClaim
    plural: postgresqlclaims
  connectionSecretKeys:
    - endpoint
    - username
    - password
    - database

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [parameters]
              properties:
                parameters:
                  type: object
                  required: [size]
                  properties:
                    size:
                      type: string
                      enum: [small, medium, large]
                      default: small
                    version:
                      type: string
                      default: "15"
                      enum: ["14", "15", "16"]
                    database:
                      type: string
                      default: appdb
                    username:
                      type: string
                      default: appuser
                writeConnectionSecretToRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
