# sync-wave 1: repo secret must exist before ArgoCD tries to clone the repo
apiVersion: v1
kind: Secret
metadata:
  name: demo-app-repo                    # e.g. team-a-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  type: git
  url: git@github.com:danielweber90/idp-poc-demo-app.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDSlBuMEpWRVpJNU55NXFKL000clpYMDBTZ0NGUnNvZTdqVXhUK1JvdGxiZ0FBQUpqbkQ0MDQ1dytOCk9BQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ0pQbjBKVkVaSTVOeTVxSi9NNHJaWDAwU2dDRlJzb2U3alV4VCtSb3RsYmcKQUFBRURvNk5uNUF6cUFaMitCZzAzSDdlckxLaUk4Y0h0NkF0bDExRFZNWVo5am1vaytmUWxVUmtqazNMbW9uOHppdGxmVApSS0FJVkd5aDd1TlRGUDVHaTJWdUFBQUFFV0Z5WjI5alpDMWtaWEJzYjNrdGEyVjVBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:danielweber90/idp-poc-demo-app.git
    targetRevision: main
    path: deploy
    helm:
      releaseName: demo-app
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
