# sync-wave 1: repo secret must exist before ArgoCD tries to clone the repo
apiVersion: v1
kind: Secret
metadata:
  name: demo-app-repo                    # e.g. team-a-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  type: git
  url: git@github.com:danielweber90/idp-poc-demo-app.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCFZ1YxBGUn6gasD+i4O+i6TRNchK8fxK7BeBAOLaoYIwAAAJihfZSPoX2U
    jwAAAAtzc2gtZWQyNTUxOQAAACCFZ1YxBGUn6gasD+i4O+i6TRNchK8fxK7BeBAOLaoYIw
    AAAEDPpzJJCdgrVRhDLXGf7fEToaIkbXjKho/osRvAaZGctYVnVjEEZSfqBqwP6Lg76LpN
    E1yErx/ErsF4EA4tqhgjAAAAEWFyZ29jZC1kZXBsb3kta2V5AQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:danielweber90/idp-poc-demo-app.git
    targetRevision: main
    path: helm
    helm:
      releaseName: demo-app
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
