apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-web-app-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/danielweber90/e2e-web-app-demo.git
    targetRevision: main
    path: helm
    helm:
      releaseName: e2e-web-app-demo
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: team-e2e-web-app-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
