replicaCount: 2
image:
  repository: "084375542523.dkr.ecr.eu-central-1.amazonaws.com/idp-poc/demo-app"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 256Mi }
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"
podLabels:
  backstage.io/kubernetes-id: demo-app
